[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
saturn_v_1 = "6y1CpFjLdNfs5KUh1PfkjS11FiwH5ZrxmeMtJm9yLdJF"

[programs.localnet]
saturn_v_1 = "6y1CpFjLdNfs5KUh1PfkjS11FiwH5ZrxmeMtJm9yLdJF"
meteora = "24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi"

[test.validator]
url = "https://api.mainnet-beta.solana.com" 

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "./tests/mainnet-dump/usdc.json"

[[test.validator.account]]
address = "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"
filename = "./tests/mainnet-dump/bonk.json"

[[test.validator.account]]
address = "GbNJigVGMPgn9qhfmTDtc1yxhX6ppnuD5bMpRe23nE2k"
filename = "./tests/mainnet-dump/user_usdc_token_account_200.json"

[[test.validator.account]]
address = "CdYZ7op8CwNKf3HjnYtXk4H7AYjaUbfZKQtECmhdmxCu"
filename = "./tests/mainnet-dump/user_bonk_token_account_200k.json"

[[test.genesis]]
address = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
program = "./tests/mainnet-dump/jupiter.so"

[[test.genesis]]
address = "HDwcJBJXjL9FpJ7UBsYBtaDjsBUhuLCUYoz3zr8SWWaQ"
program = "./tests/mainnet-dump/BPF_ungradeable_loader.so"

[[test.genesis]]
address = "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo"
program = "./tests/mainnet-dump/dlmm.so"

[[test.genesis]]
address = "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK"
program = "./tests/mainnet-dump/ray_concentrated_lp.so"

[[test.genesis]]
address = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
program = "./tests/mainnet-dump/pyth_solana_receiver.so"

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "./tests/mainnet-dump/bpf_loader2.so"

[[test.genesis]]
address = "pythWSnswVUd12oZpeFP8e9CVaEqJg25g1Vtc2biRsT"
program = "./tests/mainnet-dump/pyth_push_oracle.so"

[[test.validator.clone]]
address = "EXrqY7jLTLp83H38L8Zw3GvGkk1KoQbYTckPGBghwD8X"
[[test.validator.clone]]
address = "A8kEy5wWgdW4FG593fQJ5QPVbqx1wkfXw9c4L9bPo2CN"
[[test.validator.clone]]
address = "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo"
[[test.validator.clone]]
address = "8kR2HTHzPtTJuzpFZ8jtGCQ9TpahPaWbZfTNRs2GJdxq"
[[test.validator.clone]]
address = "EeThDNkUuNhJFHYqR3yTB6wzcj1hrubgVQuvSSGjNt4W"
[[test.validator.clone]]
address = "EXrqY7jLTLp83H38L8Zw3GvGkk1KoQbYTckPGBghwD8X"
[[test.validator.clone]]
address = "A8kEy5wWgdW4FG593fQJ5QPVbqx1wkfXw9c4L9bPo2CN"
[[test.validator.clone]]
address = "G4CD7aqqZZ6QKCNHrc1MPdS9Aw8BWmQ5ZkDd54W6mAEG"
[[test.validator.clone]]
address = "BuqEDKUwyAotZuK37V4JYEykZVKY8qo1zKbpfU9gkJMo"
[[test.validator.clone]]
address = "BuqEDKUwyAotZuK37V4JYEykZVKY8qo1zKbpfU9gkJMo"
[[test.validator.clone]]
address = "6mK4Pxs6GhwnessH7CvPivqDYauiHZmAdbEFDpXFk9zt"
[[test.validator.clone]]
address = "6P4tvbzRY6Bh3MiWDHuLqyHywovsRwRpfskPvyeSoHsz"
[[test.validator.clone]]
address = "D6XNrxMsDoABJVVY5YyHxJuAB6WGzYCXpZeKyNtqu2v4"
[[test.validator.clone]]
address = "5rCf1DM8LjKTw4YqhnoLcngyZYeNnQqztScTogYHAS6"
[[test.validator.clone]]
address = "3msVd34R5KxonDzyNSV5nT19UtUeJ2RF1NaQhvVPNLxL"
[[test.validator.clone]]
address = "6LXutJvKUw8Q5ue2gCgKHQdAN4suWW8awzFVC6XCguFx"
[[test.validator.clone]]
address = "9iFER3bpjf1PTTCQCfTRu17EJgvsxo9pVyA9QWwEuX4x"
[[test.validator.clone]]
address = "8sLbNZoA1cfnvMJLPfp98ZLAnFSYCFApfJKMbiXNLwxj"
[[test.validator.clone]]
address = "3MsJXVvievxAbsMsaT6TS4i6oMitD9jazucuq3X234tC"
[[test.validator.clone]]
address = "4gPzKMT68i89kc8whamW5yGgRRMrYw5pjqUiHkvwQS1j"
[[test.validator.clone]]
address = "DoPuiZfJu7sypqwR4eiU7C5TMcmmiFoU4HaF5SoD8mRy"
[[test.validator.clone]]
address = "2W7aa5mVuzJiaM43uFtutVFdSoWx963AKT8dtizqejTF"
[[test.validator.clone]]
address = "3nLYkE5zHKgGBxXW8Rj4neWZT5JHgdAjVRqUDcDk8nF9"
[[test.validator.clone]]
address = "AddressLookupTab1e1111111111111111111111111"

[[test.validator.clone]]
address = "5gxPdahvSzcKySxXxPuRXZZ9s6h8hZ88XDVKavWpaQGn"
[[test.validator.clone]]
address = "DaWUKXCyXsnzcvLUyeJRWou8KTn7XtadgTsdhJ6RHS7b"
[[test.validator.clone]]
address = "51wNEbR5PAvV3jcCMEhL9baqbYj7x32T7AKDu8NPKfkw"
[[test.validator.clone]]
address = "GbNJigVGMPgn9qhfmTDtc1yxhX6ppnuD5bMpRe23nE2k"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/tonicallum/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 50000