[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
saturn_v_1 = "HqWuLVZLBZ5MbDNvLqieWiERNNmpTBG7q5t99CtmGYQa"

[programs.localnet]
saturn_v_1 = "HqWuLVZLBZ5MbDNvLqieWiERNNmpTBG7q5t99CtmGYQa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
