[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
saturn_v1 = "5mWSmPkAEesVq134hxA1gqFiwDXLArUacKXfmbmXwBBt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
