[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
saturn_v1 = "GSQceBxFJCJBd4Wo5enf9GB4Qr1nXcXjfATbMR8EUqmK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
